// Copyright 2019-2025 @polkassembly/polkassembly authors & contributors
// This software may be modified and distributed under the terms
// of the Apache-2.0 license. See the LICENSE file for details.

export default `Terms of Website Use
====================

Please read these terms and conditions carefully before using this site

This terms of use (together with the documents referred to in it) tells you the terms of use on which you may make use of our website polkassembly.io (our site), whether as a guest or a registered user. Use of our site includes accessing, browsing, or registering to use our site.

Please read these terms of use carefully before you start to use our site, as these will apply to your use of our site. We recommend that you print a copy of this for future reference.

By using our site, you confirm that you accept these terms of use and that you agree to comply with them.

If you do not agree to these terms of use, you must not use our site.

### Other applicable terms

These terms of use refer to the following additional terms, which also apply to your use of our site:

-   Our Polkassembly Terms and Conditions, which set out the terms of your use of Polkassembly if you create an account and sign up.

-   Our Privacy Notice which sets out information about how we use your personal information.

-   Our Cookie Policy, which sets out information about the cookies on our site.

### Information about us

polkassembly.io is a site operated by Premiurly OÜ ("We"). We are registered in Estonia under company number 16162207 and have our registered office at Tornimäe tn 7, Kesklinna linnaosa, Tallinn, Harju maakond, 10145.

### Changes to these terms

We may revise these terms of use at any time by amending this page. Please check this page from time to time to take notice of any changes we made, as they are binding on you.

### Changes to our site

We may update our site from time to time, and may change the content at any time. However, please note that any of the content on our site may be out of date at any given time, and we are under no obligation to update it. We do not guarantee that our site, or any content on it, will be free from errors or omissions.

### Accessing our site

Our site is made available free of charge.

We do not guarantee that our site, or any content on it, will always be available or be uninterrupted. Access to our site is permitted on a temporary basis. We may suspend, withdraw, discontinue or change all or any part of our site without notice. We will not be liable to you if for any reason our site is unavailable at any time or for any period.

You are responsible for making all arrangements necessary for you to have access to our site.

You are also responsible for ensuring that all persons who access our site through your internet connection are aware of these terms of use and other applicable terms and conditions, and that they comply with them.

### Intellectual property rights

We are the owner or licensee of all intellectual property rights in our site and its content including the Premiurly OÜ name and mark. Those works are protected by intellectual property laws and treaties around the world. All such rights are reserved.

You are not granted any right to use, and may not use, any of our intellectual property rights other than as set out in these terms. You must not commercially exploit our site (or any part of it or its content); however, you may download material from our site solely for internal, non-commercial, personal use by you.

Save as required by applicable law, you shall not copy, reproduce, republish, upload, re-post, modify, transmit, distribute or otherwise use in any way for any non-personal, public or commercial purpose any part of our site including (without limitation) the text, designs, graphics, photographs, images and content generated by users without our prior written consent and (in the case of content generated by a user) the prior written consent of that user.

Our status (and that of any identified contributors) as the authors of content on our site must always be acknowledged.

If you use our site or any part of it or content on it in breach of these terms of use, your right to use our site will cease immediately and you must, at our option, return or destroy any copies of the materials you have made.

### No reliance on information

The content on our site is provided for general information only. It is not intended to amount to advice on which you should rely. You must obtain professional or specialist advice before taking, or refraining from, any action on the basis of the content on our site.

Although we make reasonable efforts to update the information on our site, we make no representations, warranties or guarantees, whether express or implied, that the content on our site is accurate, complete or up-to-date.

### Limitation of our liability

Nothing in these terms of use excludes or limits our liability for death or personal injury arising from our negligence, or our fraud or fraudulent misrepresentation, or any other liability that cannot be excluded or limited by Estonian law.

To the extent permitted by law, we exclude all conditions, warranties, representations or other terms which may apply to our site or any content on it, whether express or implied.

We will not be liable to any user for any loss or damage, whether in contract, tort (including negligence), breach of statutory duty, or otherwise, even if foreseeable, arising under or in connection with:

-   use of, or inability to use, our site; or

-   use of or reliance on any content displayed on our site.

If you are a business user, please note that in particular, we will not be liable for:

-   loss of profits, sales, business, or revenue;

-   business interruption;

-   loss of anticipated savings;

-   loss of business opportunity, goodwill or reputation; or

-   any indirect or consequential loss or damage.

If you are a consumer user, please note that we only provide our site for domestic and private use. You agree not to use our site for any commercial or business purposes, and we have no liability to you for any loss of profit, loss of business, business interruption, or loss of business opportunity.

We will not be liable for any loss or damage caused by a virus, distributed denial-of-service attack, or other technologically harmful material that may infect your computer equipment, computer programs, data or other proprietary material due to your use of our site or to your downloading of any content on it, or on any website linked to it.

We assume no responsibility for the content of websites linked on our site. Such links should not be interpreted as endorsement by us of those linked websites. We will not be liable for any loss or damage that may arise from your use of them.

### Content uploaded to our site

The views expressed by other users on our site do not represent our views or values. We take no responsibility for, and we do not expressly or implicitly endorse, any content – whether it be pictures, text, sound recordings or whatever - supplied or uploaded by a User to our site (“User Generated Content”).

We do not oversee, monitor or moderate any User Generated Content which is uploaded to our site. If you become aware of any User Generated Content that is:

-   is obscene, abusive, offensive or racist and promotes or proposes hatred or physical harm against anyone;

-   harasses, bullies, insult or intimidates another person;

-   Is false or dishonest so far as you know;

-   constitutes pornography or is sexual or sexually suggestive involving minors;

-   is defamatory of anyone;

-   uses the material or content or infringes the rights or privacy of anyone else;

-   contains someone else’s personal details or confidential information relating to other people;

-   promotes discrimination, whether based on race, sex, religion, nationality, disability, sexual orientation or age;

-   promotes or condones terrorism, violence or illegal behaviour;

-   is harmful to minors in any way;

-   promotes illegal activity or is otherwise unlawful;

-   impersonates any person, or misrepresents your identity or affiliation with any person; and

-   gives the impression that it emanates from or is endorsed by Premiurly OÜ, if this is not the case,

then please contact us on contact@premiurly.in, providing details of: (i) the date on which it was posted and where it can be found on our site; (ii) the name and surname of the author or, if the author is a legal person, the author's business name; (iii) reasons why the content should be deleted; and (vi) copies of any communication with the author (if any).

### Viruses

We do not guarantee that our site will be secure or free from bugs or viruses.

You are responsible for configuring your information technology, computer programmes and platform in order to access our site. You should use your own virus protection software.

You must not misuse our site by knowingly introducing viruses, trojans, worms, logic bombs or other material which is malicious or technologically harmful. You must not attempt to gain unauthorised access to our site, the server on which our site is stored or any server, computer or database connected to our site. You must not attack our site via a denial-of-service attack or a distributed denial-of service attack. By breaching this provision, you would commit a criminal offence under the Computer Misuse Act 1990. We will report any such breach to the relevant law enforcement authorities and we will co-operate with those authorities by disclosing your identity to them. In the event of such a breach, your right to use our site will cease immediately.

### Linking to our site

You may link to our home page, provided you do so in a way that is fair and legal and does not damage our reputation or take advantage of it.

You must not establish a link in such a way as to suggest any form of association, approval or endorsement on our part where none exists.

We reserve the right to withdraw linking permission without notice.

If you wish to make any use of content on our site other than that set out above, please contact contact@premiurly.in.

### Third party links and resources in our site

Where our site contains links to other sites and resources provided by third parties, these links are provided for your information only.

We have no control over the contents of those sites or resources.

### Applicable law

If you are a consumer, please note that these terms of use, its subject matter and its formation, are governed by the law of Estonia. You and we both agree that the courts of Estonia will have non-exclusive jurisdiction.

If you are a business, these terms of use, its subject matter and its formation (and any non-contractual disputes or claims) are governed by the law of Estonia. We both agree to the exclusive jurisdiction of the courts of Estonia.

Terms and conditions of use of materials
========================================

We, Premiurly OÜ (the "Company"), may provide publications, briefings, newsletters and presentations (the "Materials") on our site or via email and other channels. Access to the Materials is provided on the basis of the terms and conditions set out below. Please read these terms carefully before accessing the Materials.

The Materials are for general information only and are not intended to provide advice.

We do not accept responsibility or liability to users or any third parties in relation to the use of the Materials or their contents.

All copyright, trade marks and other intellectual property in or arising out of the Materials vest solely in us.

You agree not to modify, reproduce, copy, distribute, disclose to third parties or derive commercial use or benefit from the Materials without our prior written consent.

You agree not to use or permit the use of the Materials for any illegal purpose nor use the materials in such a manner as would bring us or our business into disrepute.

Nothing in these terms shall operate to exclude or restrict liability based on fraud or reckless disregard of professional obligations or any other liability that cannot be excluded or restricted by applicable laws or regulations.

These terms shall be construed in accordance with the laws of Estonia.

### Contact us

To contact us, please email contact@premiurly.in.

Statutory information
---------------------

Statutory information about Premiurly OÜ:

-   Registered in Estonia

-   Registered Number: 16162207

-   Registered Office: Tornimäe tn 7, Kesklinna linnaosa, Tallinn, Harju maakond, 10145.

Thank you for visiting our site.
`;
