name: Code Review

permissions:
  contents: read
  pull-requests: write

on:
  push:
    branches:
      - preview

jobs:
  check_branch_and_review:
    runs-on: ubuntu-latest
    if:
      contains('refs/heads/preview', github.ref)
    steps:
      - uses: coderabbitai/ai-pr-reviewer@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        with:
          debug: true
          review_comment_lgtm: false
          openai_heavy_model: gpt-3.5-turbo
          path_filters: |
            !.next/**
            !**/*.lock